# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: RedgateSqlChangeAutomationBuild@3
  inputs:
    operation: 'Build SQL Change Automation Project'
    packageName: 'StackOverflow'
    tempServerTypeBuild: 'localDB'
    nugetPackageVersionSelector: 'Specific'
    nugetPackageVersion: '0.$(Build.BuildId)'
    requiredVersionOfDlma: 'latest'
